trigger: none
  #branches:
  #  include:
   #   - main

pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
  - repository: test1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: shivgithub
    name: shikari1893/ado1
    ref: main
    trigger:
     branches:
        include:
          - main
          
  - repository: org
    type: github
    endpoint: shivgithub
    name: shiv2192612/test
    #trigger:
    #- main
    

    pr:
     branches:
      include:
      - main
#pr:
#  branches:
#    include:
#      - main      
    

steps:
  - checkout: self
  - checkout: test1
  - bash: | 
      ls
              
