trigger: none

pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
  - repository: test1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: shivgithub
    name: shikari1893/ado1
    #ref: refs/heads/main
    trigger:
     branches:
      include:
        - main
      
    

steps:
  - checkout: self
  - checkout: test1
  - bash: | 
      ls
              
