trigger: none

pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
  - repository: test1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: shivgithub
    name: shiv/ado
    #ref: refs/heads/main
    trigger:
     branches:
      include:
        - main
      
    

stages:
- stage: CheckoutCode
  jobs:
  - job: CheckoutCode
    steps: 
    - checkout: self # checkout code in the CLIIP repository
    - bash: |
              ls -l
              
